include $(GOROOT)/src/Make.inc

TARG=walk/gui
GOFILES=\
	action.go\
	actionlist.go\
	application.go\
	boxlayout.go\
	button.go\
	checkbox.go\
	combobox.go\
	comboboxitem.go\
	comboboxitemlist.go\
	commondialogs.go\
	composite.go\
	container.go\
	customwidget.go\
	dialog.go\
	groupbox.go\
	gui.go\
	imagelist.go\
	label.go\
	lineedit.go\
	listviewcolumn.go\
	listviewcolumnlist.go\
	listview.go\
	listviewitem.go\
	listviewitemlist.go\
	mainwindow.go\
	menu.go\
	messagebox.go\
	observedwidgetlist.go\
	progressbar.go\
	pushbutton.go\
	radiobutton.go\
	simpletypes.go\
	splitter.go\
	textedit.go\
	toolbar.go\
	tooltip.go\
	treeview.go\
	treeviewitem.go\
	treeviewitemlist.go\
	util.go\
	widget.go

include $(GOROOT)/src/Make.pkg
