include $(GOROOT)/src/Make.inc

TARG=walk/winapi
GOFILES=\
	advapi32.go\
	combobox.go\
	comctl32.go\
	comdlg32.go\
	datetimepicker.go\
	edit.go\
	gdi32.go\
	gdiplus.go\
	kernel32.go\
	listview.go\
	menu.go\
	ole32.go\
	oleaut32.go\
	shdocvw.go\
	shell32.go\
	tab.go\
	toolbar.go\
	tooltip.go\
	treeview.go\
	updown.go\
	user32.go\
	uxtheme.go\
	winapi.go\
	winspool.go\

include $(GOROOT)/src/Make.pkg
