include $(GOROOT)/src/Make.inc

TARG=walk/printing
GOFILES=\
	document.go\
	page.go\
	pageinfo.go\
	papersize.go\
	papersource.go\
	printerinfo.go\
	printing.go\
	simpletextitem.go\
	resolution.go\
	util.go

include $(GOROOT)/src/Make.pkg
