include $(GOROOT)/src/Make.inc

TARG=walk/drawing
GOFILES=\
	bitmap.go\
	brush.go\
	color.go\
	font.go\
	image.go\
	metafile.go\
	pen.go\
	point.go\
	rectangle.go\
	size.go\
	surface.go\
	util.go

include $(GOROOT)/src/Make.pkg
