include $(GOROOT)/src/Make.inc

TARG=walk/winapi/comctl32
GOFILES=\
	comctl32.go\
	datetimepicker.go\
	listview.go\
	tab.go\
	toolbar.go\
	tooltip.go\
	treeview.go\
	updown.go

include $(GOROOT)/src/Make.pkg
